// File generated by flutterfire_cli.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io';
import 'package:flutter_dotenv/flutter_dotenv.dart';

String _requiredEnv(String key) {
  final value = dotenv.env[key]?.trim();
  final invalid =
      value == null ||
      value.isEmpty ||
      value.startsWith('YOUR_') ||
      value.contains('_here') ||
      value.startsWith('your-') ||
      value.startsWith('your_');

  if (invalid) {
    throw StateError(
      'Variable Firebase invalide: $key. '
      'Mets une vraie valeur dans .env (pas un placeholder).',
    );
  }

  return value;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isLinux || Platform.isMacOS || Platform.isWindows) {
      return android; // Use Android config for desktop testing
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_API_KEY'),
      appId: _requiredEnv('FIREBASE_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
      databaseURL: _requiredEnv('FIREBASE_DATABASE_URL'),
      storageBucket: _requiredEnv('FIREBASE_STORAGE_BUCKET'),
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
      appId: _requiredEnv('FIREBASE_IOS_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
      databaseURL: _requiredEnv('FIREBASE_DATABASE_URL'),
      storageBucket: _requiredEnv('FIREBASE_STORAGE_BUCKET'),
      iosBundleId: _requiredEnv('FIREBASE_IOS_BUNDLE_ID'),
    );
  }
}
