// File generated by flutterfire_cli.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_platform_interface/flutter_platform_interface.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'YOUR_ANDROID_API_KEY',
      appId: dotenv.env['FIREBASE_APP_ID'] ?? 'YOUR_ANDROID_APP_ID',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'YOUR_MESSAGING_SENDER_ID',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-flutter-love-app',
      databaseURL: dotenv.env['FIREBASE_DATABASE_URL'] ?? 'https://your-flutter-love-app.firebaseio.com',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'your-flutter-love-app.appspot.com',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'YOUR_IOS_API_KEY',
      appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? 'YOUR_IOS_APP_ID',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'YOUR_MESSAGING_SENDER_ID',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-flutter-love-app',
      databaseURL: dotenv.env['FIREBASE_DATABASE_URL'] ?? 'https://your-flutter-love-app.firebaseio.com',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'your-flutter-love-app.appspot.com',
      iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.loveapp',
    );
  }
}
